server:
  port: 8080

spring:
  datasource:
    url: jdbc:mariadb://mariadb:3306/ai_diary
    username: dongha
    password: ansqhrl3037
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui/index.html

jwt:
  secret: "my-secure-jwt-secret-key-which-is-long-enough"
  expiration: 3600000

logging:
  level:
    root: INFO
    org.aidiary: DEBUG
  file:
    name: /var/log/aidiary/aidiary.log  # Docker 환경을 고려한 경로

file:
  upload-dir: /uploads/  # Docker에서 볼륨 경로 매핑 필요
